export const productsData = [
  {
    id: 0,
    image: process.env.PUBLIC_URL + "/images/FarmHouse.jpg",
    title: "2024 Farm House",
    currentBid: 100000000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Real Estate",
    subcategory: "Villas",
    region: "St Peter",
    subregion: "Subregion 1",
    subCatType: "Villas",
  },
  {
    id: 1,
    image: process.env.PUBLIC_URL + "/images/villa.jfif",
    title: "2018 Private Villa at Drass",
    currentBid: 120000000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "fixed-price",
    category: "Real Estate",
    subcategory: "Independent Houses",
    region: "St Michael",
    subregion: "Subregion 2",
    subCatType: "Real Estates",
  },
  {
    id: 2,
    image: process.env.PUBLIC_URL + "/images/Laptop.png",
    title: "2021 LG Laptop",
    currentBid: 5000,
    timeRemaining: "4",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Consumer Electronics",
    subcategory: "Laptops",
    region: "Region C",
    subregion: "Subregion 3",
    subCatType: "Laptops",
  },
  {
    id: 3,
    image: process.env.PUBLIC_URL + "/images/Mobile.png",
    title: "2015 Samsung Mobile",
    currentBid: 3800,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Cellphone and PDAs",
    subcategory: "Other",
    region: "St Lucy",
    subregion: "Subregion 4",
    subCatType: "Retail & Services",
  },
  {
    id: 4,
    image: process.env.PUBLIC_URL + "/images/Home.png",
    title: "2024 Luxury Home",
    currentBid: 3000000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "active",
    type: "classified",
    category: "Real Estate",
    subcategory: "Flats",
    region: "St Phillip",
    subregion: "Subregion 1",
    subCatType: "Flats",
  },
  {
    id: 5,
    image: process.env.PUBLIC_URL + "/images/Coffee.jpg",
    title: "2023 Coffee Estate",
    currentBid: 25000000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "classified",
    category: "Real Estate",
    subcategory: "Agriculture Lands",
    region: "St John",
    subregion: "Subregion 5",
    subCatType: "Coffee Estates",
  },
  {
    id: 6,
    image: process.env.PUBLIC_URL + "/images/HomeRealEstate.jpg",
    title: "2000 House For Sale",
    currentBid: 4000000,
    timeRemaining: "2",
    isExpired: false,
    status: "active",
    type: "auction",
    category: "Real Estate",
    subcategory: "Independent Houses",
    region: "St George",
    subregion: "Subregion 6",
    subCatType: "Independent Houses",
  },
  {
    id: 7,
    image: process.env.PUBLIC_URL + "/images/Oil painting.jfif",
    title: "19th Century Trucks",
    currentBid: 800000,
    timeRemaining: "6",
    isExpired: false,
    status: "active",
    type: "classified",
    category: "Antiques",
    subcategory: "Other Assets",
    region: "St Andrew",
    subregion: "Subregion 7",
    subCatType: "Other Assets",
  },
  {
    id: 8,
    image: process.env.PUBLIC_URL + "/images/Car.png",
    title: "2021 Maruti Cars",
    currentBid: 175000,
    timeRemaining: "3",
    isExpired: false,
    status: "active",
    type: "classified",
    category: "Automobiles",
    subcategory: "Cars",
    region: "St Thomas",
    subregion: "Subregion 3",
    subCatType: "Cars",
  },
  {
    id: 9,
    image: process.env.PUBLIC_URL + "/images/Home.png",
    title: "2021 Maruti Cars",
    currentBid: 175000,
    timeRemaining: "1",
    isExpired: true,
    status: "active",
    type: "auction",
    category: "Automobiles",
    subcategory: "Cars",
    region: "Christ Church",
    subregion: "Subregion 4",
  },
  {
    id: 10,
    image: process.env.PUBLIC_URL + "/images/SAME tractor.jfif",
    title: "SAME Tractor 40HP",
    currentBid: 900000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Automobiles",
    subcategory: "Tractor",
    region: "St Peter",
    subregion: "Subregion 1",
    subCatType: "Tractors",
  },
  {
    id: 11,
    image: process.env.PUBLIC_URL + "/images/tractor2.jfif",
    title: "Tractor-35HP",
    currentBid: 500000,
    timeRemaining: "4",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Automobiles",
    subcategory: "Tractor",
    region: "Region C",
    subregion: "Subregion 2",
    subCatType: "Tractors",
  },
  {
    id: 12,
    image: process.env.PUBLIC_URL + "/images/Truckimage.jfif",
    title: "Brand New Truck",
    currentBid: 2000000,
    timeRemaining: "4",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Automobiles",
    subcategory: "Truck",
    region: "Region C",
    subregion: "Subregion 1",
    subCatType: "Trucks",
  },
  {
    id: 13,
    image: process.env.PUBLIC_URL + "/images/truck2.jfif",
    title: "Truck for sale",
    currentBid: 1200000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Automobiles",
    subcategory: "Truck",
    region: "St Peter",
    subregion: "Subregion 1",
    subCatType: "Trucks",
  },
];

export const categoriesData = [
  {
    name: "Antiques",
    quantity: 2,
    subcategories: [{ name: "Other Assets" }, { name: "Real Estates" }],
  },
  {
    name: "Automobiles",
    quantity: 3,
    subcategories: [{ name: "Cars" }, { name: "Trucks" }, { name: "Tractors" }],
  },

  {
    name: "Consumer Electronics",
    quantity: 1,
    subcategories: [{ name: "Laptops" }],
  },

  {
    name: "Real Estate",
    quantity: 2,
    subcategories: [{ name: "Villas" }, { name: "Independent Houses" }],
  },
];

export const regionsData = [
  {
    name: "Region A",
    quantity: 2,
    subregions: [{ name: "Subregion 1" }, { name: "Subregion 2" }],
  },
  {
    name: "Region B",
    quantity: 3,
    subregions: [
      { name: "Subregion 4" },
      { name: "Subregion 5" },
      { name: "Subregion 6" },
    ],
  },
  {
    name: "Region C",
    quantity: 1,
    subregions: [{ name: "Subregion 7" }],
  },
];

export const sortOptions = [
  { value: "price-lowest", label: "Price Lowest" },
  { value: "price-highest", label: "Price Highest" },
  { value: "title-a-to-z", label: "Title, A to Z" },
  { value: "title-z-to-a", label: "Title, Z to A" },
];
export const filterByOptions = [
  { value: "all", label: "All" },
  { value: "auction", label: "Auction" },
  { value: "fixed-price", label: "Fixed Price" },
  { value: "classified", label: "Classified" },
];
