export const productsData = [
  {
    id: 0,
    image: process.env.PUBLIC_URL + "/images/FarmHouse.jpg",
    title: "Farm House",
    currentBid: 10000,
    buyNow:12000,
    timeRemaining: "2",
    isExpired: false,
    status: "active",
    type: "auction",
    category: "Real Estate",
    subcategory: "Villas",
    region: "India South",
    subregion: "Bombay Region",
    subCatType: "Villas",
  },
  {
    id: 1,
    image: process.env.PUBLIC_URL + "/images/villa.jfif",
    title: "Private Villa at Drass",
    currentBid: 120000000,
    buyNow:140000000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "fixed-price",
    category: "Real Estate",
    subcategory: "Independent Houses",
    region: "St Michael",
    subregion: "Madrass Region",
    subCatType: "Real Estates",
  },
  {
    id: 2,
    image: process.env.PUBLIC_URL + "/images/laptop1.jpg",
    title: "Laptop",
    currentBid: 5000,
    buyNow:7000,
    timeRemaining: "4",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Consumer Electronics",
    subcategory: "Laptops",
    region: "India NorthEast",
    subregion: "Subregion 3",
    subCatType: "Laptops",
  },
  {
    id: 3,
    image: process.env.PUBLIC_URL + "/images/Mobile.png",
    title: "Samsung Mobile",
    currentBid: 3800,
    buyNow:5000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Consumer Electronics",
    subcategory: "Mobiles",
    region: "India North",
    subregion: "Delhi NCR Region",
    subCatType: "Mobiles",
  },
  {
    id: 4,
    image: process.env.PUBLIC_URL + "/images/villa.jfif",
    title: "Luxury Home",
    currentBid: 3000,
    buyNow:4500,
    timeRemaining: "2",
    isExpired: false,
    status: "active",
    type: "classified",
    category: "Real Estate",
    subcategory: "Flats",
    region: "St Phillip",
    subregion: "Bombay Region",
    subCatType: "Flats",
  },
  {
    id: 5,
    image: process.env.PUBLIC_URL + "/images/Coffee.jpg",
    title: "Coffee Estate",
    currentBid: 25000,
    buyNow:37000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "classified",
    category: "Real Estate",
    subcategory: "Agriculture Lands",
    region: "St John",
    subregion: "Lucknow Region",
    subCatType: "Coffee Estates",
  },
  {
    id: 6,
    image: process.env.PUBLIC_URL + "/images/HomeRealEstate.jpg",
    title: "House For Sale",
    currentBid: 40000,
    buyNow:55000,
    timeRemaining: "2",
    isExpired: false,
    status: "active",
    type: "auction",
    category: "Real Estate",
    subcategory: "Independent Houses",
    region: "St George",
    subregion: "Bengal Region",
    subCatType: "Independent Houses",
  },
  {
    id: 7,
    image: process.env.PUBLIC_URL + "/images/paint5.jfif",
    title: "Painting",
    currentBid: 80,
    buyNow:95,
    timeRemaining: "6",
    isExpired: false,
    status: "active",
    type: "classified",
    category: "Antiques",
    subcategory: "Other Assets",
    region: "St Andrew",
    subregion: "Guwahati Region",
    subCatType: "Other Assets",
  },
  {
    id: 8,
    image: process.env.PUBLIC_URL + "/images/Car.png",
    title: "Maruti Car",
    currentBid: 17500,
    buyNow:20000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Automobiles",
    subcategory: "Cars",
    region: "India-South",
    subregion: "Madrass Region",
    subCatType: "Cars",
  },
  {
    id: 9,
    image: process.env.PUBLIC_URL + "/images/Home.png",
    title: "Home",
    currentBid: 19500,
    buyNow:21500,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Automobiles",
    subcategory: "Independent House",
    region: "India-North",
    subregion: "Delhi NCR Region",
    subCatType: "Independent Houses",
  },
  {
    id: 10,
    image: process.env.PUBLIC_URL + "/images/SAME tractor.jfif",
    title: "SAME Tractor 40HP",
    currentBid: 9000,
    buyNow:12000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Automobiles",
    subcategory: "Tractor",
    region: "St Peter",
    subregion: "Bombay Region",
    subCatType: "Tractors",
  },
  {
    id: 11,
    image: process.env.PUBLIC_URL + "/images/tractor2.jfif",
    title: "Tractor-35HP",
    currentBid: 5000,
    buyNow:6500,
    timeRemaining: "4",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Automobiles",
    subcategory: "Tractor",
    region: "India NorthEast",
    subregion: "Madrass Region",
    subCatType: "Tractors",
  },
  {
    id: 12,
    image: process.env.PUBLIC_URL + "/images/Truckimage.jfif",
    title: "Brand New Truck",
    currentBid: 20000,
    buyNow:35000,
    timeRemaining: "4",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Automobiles",
    subcategory: "Truck",
    region: "India NorthEast",
    subregion: "Bombay Region",
    subCatType: "Trucks",
  },
  {
    id: 13,
    image: process.env.PUBLIC_URL + "/images/truck2.jfif",
    title: "Truck for sale",
    currentBid: 12000,
    buyNow:13000,
    timeRemaining: "Expired",
    isExpired: true,
    status: "completed",
    type: "auction",
    category: "Automobiles",
    subcategory: "Truck",
    region: "St Peter",
    subregion: "Bombay Region",
    subCatType: "Trucks",
  },
  {
    id: 14,
    image: process.env.PUBLIC_URL + "/images/Agriculture.jpg",
    title: "Agri-Land @ Guntur",
    currentBid: 1000,
    buyNow:1200,
    timeRemaining: "7",
    isExpired: false,
    status: "active",
    type: "auction",
    category: "Real Estate",
    subcategory: "Lands",
    region: "India South",
    subregion: "Madras Region",
    subCatType: "Lands",
  },
  {
    id: 15,
    image: process.env.PUBLIC_URL + "/images/building.jpg",
    title: "College Building-Mysore",
    currentBid: 30000,
    buyNow:45000,
    timeRemaining: "3",
    isExpired: false,
    status: "active",
    type: "auction",
    category: "Real Estate",
    subcategory: "Bunglow",
    region: "India South",
    subregion: "Madras Region",
    subCatType: "Bunglows",
  },
  {
    id: 16,
    image: process.env.PUBLIC_URL + "/images/bunglow2.jfif",
    title: "Resort-Bunglow@Jammu",
    currentBid: 50000,
    buyNow:50000,
    timeRemaining: "10",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Real Estate",
    subcategory: "Bunglow",
    region: "India North",
    subregion: "Delhi NCR Region",
    subCatType: "Bunglows",
  },
  {
    id: 17,
    image: process.env.PUBLIC_URL + "/images/bunglow3.jfif",
    title: "Private Bunglow",
    currentBid: 70000,
    buyNow:90000,
    timeRemaining: "1",
    isExpired: false,
    status: "active",
    type: "classified",
    category: "Real Estate",
    subcategory: "Bunglow",
    region: "India North",
    subregion: "Lucknow Region",
    subCatType: "Bunglows",
  },
  {
    id: 18,
    image: process.env.PUBLIC_URL + "/images/bunglowVillage.jpg",
    title: "Old British Bunglow",
    currentBid: 20000,
    buyNow:30000,
    timeRemaining: "11",
    isExpired: false,
    status: "active",
    type: "classified",
    category: "Real Estate",
    subcategory: "Bunglow",
    region: "India North East",
    subregion: "Guwahati Region",
    subCatType: "Bunglows",
  },
  {
    id: 19,
    image: process.env.PUBLIC_URL + "/images/bungloww.jfif",
    title: "Farm-House",
    currentBid: 10000,
    buyNow:16000,
    timeRemaining: "3",
    isExpired: false,
    status: "active",
    type: "auction",
    category: "Real Estate",
    subcategory: "Bunglow",
    region: "India South",
    subregion: "Bombay Region",
    subCatType: "Bunglows",
  },
  {
    id: 20,
    image: process.env.PUBLIC_URL + "/images/secondcar.jpg",
    title: "Vintage Car",
    currentBid: 1000,
    buyNow:1450,
    timeRemaining: "5",
    isExpired: false,
    status: "active",
    type: "classified",
    category: "automobiles",
    subcategory: "car",
    region: "India North",
    subregion: "Bengal Region",
    subCatType: "Cars",
  },
  {
    id: 21,
    image: process.env.PUBLIC_URL + "/images/landforrent.jfif",
    title: "Land(open) for Rent",
    currentBid: 500,
    buyNow:50000,
    timeRemaining: "3",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Real Estate",
    subcategory: "Land",
    region: "India North",
    subregion: "Lucknow Region",
    subCatType: "Lands",
  },
  {
    id: 22,
    image: process.env.PUBLIC_URL + "/images/house3bhk.avif",
    title: "House-3BHK for Rent",
    currentBid: 700,
    buyNow:40000,
    timeRemaining: "6",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Real Estate",
    subcategory: "Independent House",
    region: "India North East",
    subregion: "Guwahati Region",
    subCatType: "Independent Houses",
  },
  {
    id: 23,
    image: process.env.PUBLIC_URL + "/images/house23.jpg",
    title: " For Shooting @Hyderabad",
    currentBid: 7000,
    buyNow:11000,
    timeRemaining: "8",
    isExpired: false,
    status: "active",
    type: "auction",
    category: "Real Estate",
    subcategory: "Independent House",
    region: "India North",
    subregion: "Delhi NCR Region",
    subCatType: "Independent Houses",
  },
  {
    id: 24,
    image: process.env.PUBLIC_URL + "/images/layout.jfif",
    title: "30*40 Sites @ Hosur",
    currentBid: 500,
    buyNow:500,
    timeRemaining: "7",
    isExpired: false,
    status: "active",
    type: "fixed-price",
    category: "Real Estate",
    subcategory: "Land",
    region: "India South",
    subregion: "Madras Region",
    subCatType: "Lands",
  },
  {
    id: 25,
    image: process.env.PUBLIC_URL + "/images/painting.png",
    title: "Oil Paint-Kishan",
    currentBid: 400,
    buyNow:500,
    timeRemaining: "7",
    isExpired: false,
    status: "active",
    type: "classified",
    category: "Antique",
    subcategory: "Other Assets",
    region: "India North",
    subregion: "Lucknow Region",
    subCatType: "Other Assets",
  },
  {
    id: 26,
    image: process.env.PUBLIC_URL + "/images/resorts.jpg",
    title: "Resort @ Munnar",
    currentBid: 4000,
    buyNow:5000,
    timeRemaining: "1",
    isExpired: false,
    status: "active",
    type: "auction",
    category: "Real Estate",
    subcategory: "villas",
    region: "India South",
    subregion: "Madras Region",
    subCatType: "Villas",
  },
];

export const categoriesData = [
  {
    name: "Antiques",
    quantity: 2,
    subcategories: [{ name: "Other Assets" }, { name: "Real Estates" }],
  },
  {
    name: "Automobiles",
    quantity: 3,
    subcategories: [{ name: "Cars" }, { name: "Trucks" }, { name: "Tractors" }],
  },

  {
    name: "Consumer Electronics",
    quantity: 1,
    subcategories: [{ name: "Laptops" },{ name: "Mobiles" }],
  },

  {
    name: "Real Estate",
    quantity: 4,
    subcategories: [{ name: "Villas" }, { name: "Independent Houses" },{ name: "Lands" },{ name: "Bunglows" } ],
  },
];

export const regionsData = [
  {
    name: "India-South",
    quantity: 2,
    subregions: [{ name: "Bombay Region" }, { name: "Madras Region" }],
  },
  {
    name: "India-North",
    quantity: 3,
    subregions: [
      { name: "Delhi NCR Region" },
      { name: "Lucknow Region" },
      { name: "Bengal Region" },
    ],
  },
  {
    name: "India North East",
    quantity: 1,
    subregions: [{ name: "Guwahati Region" }],
  },
];

export const sortOptions = [
  { value: "price-lowest", label: "Price Lowest" },
  { value: "price-highest", label: "Price Highest" },
  { value: "title-a-to-z", label: "Title, A to Z" },
  { value: "title-z-to-a", label: "Title, Z to A" },
];
export const filterByOptions = [
  { value: "all", label: "All" },
  { value: "auction", label: "Auction" },
  { value: "fixed-price", label: "Fixed Price" },
  { value: "classified", label: "Classified" },
];
export const currencyOptions =[
  { label: " Dollar (USD)", value: "$"},
  { label: " Rupees (INR)", value: "₹"},
  { label: " Euro (EUR)", value: "€"},
  { label: " Yen (JPY)", value: "¥"}
];
